const mongoose = require('mongoose');
const { v4: uuidv4 } = require('uuid');

/**
 * Batch — represents one academic batch e.g. "2023-2027"
 * Manager creates a Batch → 8 Semesters are auto-generated by the service.
 */
const batchSchema = new mongoose.Schema(
    {
        uid: { type: String, default: uuidv4, unique: true, index: true },

        name: {
            type: String,
            required: [true, 'Batch name is required. e.g. 2023-2027'],
            trim: true,
        },
        startYear: {
            type: Number,
            required: [true, 'Start year is required.'],
        },
        endYear: {
            type: Number,
            required: [true, 'End year is required.'],
        },
        institution: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Institution',
            required: [true, 'Institution is required.'],
        },
        createdBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            required: true,
        },
        isActive: { type: Boolean, default: true },
        isArchived: { type: Boolean, default: false },
    },
    { timestamps: true, versionKey: false }
);

const Batch = mongoose.model('Batch', batchSchema);
module.exports = Batch;

// © 2026 Syed Khubayb Ur Rahman
// GitHub: https://github.com/kh-ub-ayb
